FROM node:20-alpine

WORKDIR /app

# Instala Angular CLI globalmente
RUN npm install -g @angular/cli@18

# Copia arquivos de dependências
COPY package*.json ./

# Instala dependências
RUN npm install

# Copia todo o código fonte
COPY . .

# Expõe a porta 4200
EXPOSE 4200

# Comando para executar o Angular com proxy
CMD ["ng", "serve", "--host", "0.0.0.0", "--proxy-config", "proxy.conf.json", "--poll", "2000"]
